---
output:
  word_document:
    fig_caption: true
    fig_height: 10
    fig_width: 10
    reference_docx: bootstrap/initial/data/summaryTemplate.docx
    toc: false
    keep_md: false
params:
  summary_title: ""
  strata: NULL
---


```{r introduction, include = FALSE}

# INTRODUCTION ################################################################

# This markdown documents and integrated scripts analyse biological
# age readings.
# The output is a .docx template that includes
# the results of the analysis and should be used as a standard for
# reporting of age reading comparisons.

```

```{r chunk_setup, include=FALSE}
# CHUNK SETUPS #################################################################

knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message=FALSE, results = 'asis', dpi=400)

```


```{r pander_settings, include = FALSE}

# PANDER OPTIONS ##############################################################

panderOptions('table.split.table', Inf)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('table.alignment.default', "center")
panderOptions('knitr.auto.asis', FALSE)

group <- "adv"

# from extrafont
# font_import(pattern=c("Cali"))
# loadfonts(device="win")
```

---
title: `r params$summary_title`
---

# Executive summary


# Overview of samples and advanced readers


\br

```{r sample_overview}

modal_age_range <- range(ad_long_all$modal_age, na.rm = TRUE)
# Table caption
set.caption(paste('**Table X:** Overview of samples used for the exchange event', config$event_id, '. The modal age range for all samples is ', modal_age_range[1], "-", modal_age_range[2], '.', sep=""))

# Output table
pander(style_table0(sample_data_overview), style = "simple")

```

\br

```{r participants_overview}

# PARTICIPATANTS OVERVIEW #####################################################

# Table caption
set.caption('**Table X:** Overview of number of readers.')

# Output table
datab=filter(reader_data, Expertise!="Basic")
selvar=colnames(datab)[-c(1, 3)]
datab=ddply(datab, c(selvar), summarise, N_readers=length(Expertise))
pander(style_table0(datab))
```

*Overview table*

<!-- Stock, total number of samples (NSample), PA, CV, APE, numer of readers (basic and advance) -->
```{r overview_statistics_all}
overview_statistics_all <-
    c(Stock=unique(ad_long_all$stock),
    NSample  = length(unique(ad_long_all$SampleID)),
    CV  = cv_tab_all[nrow(cv_tab_all), "all"],
    PA  = pa_tab_all[nrow(pa_tab_all), "total"],
    APE = ape_tab_all[nrow(ape_tab_all), "all"],
    N_basic=length(unique(ad_long_all$reader))-length(unique(ad_long_adv$reader)),
    N_adv=length(unique(ad_long_adv$reader)))

# Table caption
set.caption('**Table X:** Overview results: Stock, total number of samples (NSample), coefficient of variance (CV), percentage of agreement (PA),  average percentage error (APE) for all ages and readers and the number of readers (basic [N_basic] and advanced [N_advanced]) on the event.')

# Output table
pander(style_table0(overview_statistics_all), missing="")

```


<!-- ## Advanced readers -->

<!-- **All samples included**  -->

# Results overview

## Multimodal cases

<!-- Total number of samples (NSample), number (CountMM) and percentage of multimodal cases (PercMM) text -->
```{r summary_multiple_modes}
summary_multiple_modes <-
    c(NSample  = length(unique(ad_long_adv$SampleID)),
    PercMM_traditional=unique(ifelse(multimode_cases_tab_traditional_adv$NModes_trad=="zero", paste(0,"%"), paste(round((nrow(multimode_cases_tab_traditional_adv)/length(unique(ad_long_adv$SampleID)))*100, digits=0),"%"))),
    PercMM_linear_weight=unique(ifelse(multimode_cases_tab_linear_adv$NModes_linear=="zero", paste(0,"%"), paste(round((nrow(multimode_cases_tab_linear_adv)/length(unique(ad_long_adv$SampleID)))*100, digits=0),"%"))),
    PercMM_negexp_weight=unique(ifelse(multimode_cases_tab_negexp_adv$NModes_negexp=="zero", paste(0,"%"), paste(round((nrow(multimode_cases_tab_negexpweight_adv)/length(unique(ad_long_adv$SampleID)))*100, digits=0),"%"))),
    PercMM_multistage=unique(ifelse(multimode_cases_tab_multistage_adv$NModes_multistage=="zero", paste(0,"%"), paste(round((nrow(multimode_cases_tab_multistage_adv)/length(unique(ad_long_adv$SampleID)))*100, digits=0),"%"))))

# Table caption
set.caption('**Table X:** Summary of statistics; Total number of samples (NSample), a percentage of cases (fish samples) with multiple modes depending on the approach to weight the experience of the reader which will be considered when defining the fish age mode. PercMM_traditional shows the percentage of the total samples for which multiple modes are obtained when all the readers are equally weighted. PercMM_linear_weight shows the percentage of the total samples for which multiple modes are obtained when the weight assigned to the different readers decreases linearly with the experience, while in the PercMM_negexp the weight applied decreases with a negative exponential shape with the experience. The PercMM_multistage shows the percentage of multiple mode cases when a combination of the different methodologies is used, as explained in the material and methods section')

# Output table
pander(style_table0(summary_multiple_modes), missing="")

```

## Age readings

```{r num_read_adv}

# Age readings TABLE - Advanced readers #################################################

# Table caption
set.caption('**Table X:** Age reading table shows the
             number of readings by modal age.')

# Output table
pander(style_table1(num_read_tab_adv[,colnames(num_read_tab_adv) %in% c("Modal age", "total")]), missing = "-")

```


## CV table

```{r cv_adv}

# CV TABLE - Advanced readers #################################################

# Table caption
set.caption('**Table X:** Coefficient of Variation (CV) table presents the
             CV per modal age for all advanced readers combined.')

# Output table
pander(style_table1(cv_tab_adv[,colnames(cv_tab_adv) %in% c("Modal age", "all")]), missing = "-")

```

## PA table

```{r percentage_agreement_adv}

# PERCENTAGE AGREEMENT TABLE - Advanced readers ###############################

# Table caption
set.caption('**Table X:** Percentage agreement (PA) table represents the PA per
             modal age for all advanced readers combined.')

# Output table
pander(style_table1(pa_tab_adv[,colnames(pa_tab_adv) %in% c("Modal age", "total")]), missing = "-")

```


## APE table

```{r average_percentage_error_adv}

# AVERAGE PERCENTAGE ERROR TABLE - Advanced readers ###############################

# Table caption
set.caption('**Table X:** Average Percentage Error (APE) table represents the APE per
             modal age for all advanced readers combined.')

# Output table
pander(style_table1(ape_tab_adv[,colnames(ape_tab_adv) %in% c("Modal age", "all")]), missing = "-")

```



## Relative bias table

```{r rb_adv,results='asis'}

# RELATIVE BIAS TABLE - Advanced readers ######################################

# Table caption
set.caption('**Table X:** The relative bias (as the difference between the mean and modal age) per
             modal age for all advanced readers combined.')

# Output table
pander(style_table1(rel_bias_tab_adv[,colnames(rel_bias_tab_adv) %in% c("Modal age", "all")]), missing = "-")

```

## Bias plot

```{r bias_plots_exp, fig.width = 5, fig.height = 4, fig.cap = cap_in}

# BIAS PLOT - Advanced readers ################################################

# Table caption
cap_in <- '**Figure X:** Age bias plot for advanced readers.'

# Output table
plot_bias_all(ad_long_adv, max_age, max_modal, sel_readers="Advanced readers")

```

\br


## Growth analysis

```{r growth_analysis_exp, fig.width = 6, fig.height = 4, fig.cap = cap_in}
# GROWTH ANALYSIS - Advanced readers ##########################################

# Table caption
cap_in <- '**Figure X:** Plot of average distance from the centre to the winter
           rings for advanced readers. The boxes represent 
           the median, upper and lower box boundaries of the interquartile range,
           whiskers extend no further than 1.5 * IQR (where IQR is the inter-quartile 
           range) from the box boundary. Data beyond the end of the whiskers are 
           represent outlers and are plotted individually.'

# Output table
plot_growth(dist, ad_long_all, stratif = "no_stratification")
```

## Age error matrices AEM

### General Age Error Matrix (AEM)

```{r age_error_matrix_adv, results='asis'}

# General AEM - Advanced readers #################################################

# Table caption
  cap_i <- "**Table X:** General Age error matrix (AEM). The modal age is in rows and the age classifications by the advanced readers in columns."
  set.caption(cap_i)
  pander(style_table3(ae_mat_adv[[1]]), missing = "-")

```

### AEM by ICES area

```{r age_error_matrix_by_area_adv, results='asis'}

# AEM by area - Advanced readers #################################################

# Loop through each area and output AEM for that area
for (i in seq_along(ae_mat_by_area_adv)) {
  # name of strata
  ices_area <- names(ae_mat_by_area_adv)[i]
  
  # Table caption
  cap_i <- paste0("**Table X:** Age error matrix (AEM) for ICES area ", ices_area,".")

  set.caption(cap_i)
  pander(style_table3(ae_mat_by_area_adv[[i]]), missing = "-")

}

```

### AEM by strata

```{r age_error_matrix_by_strata_adv, results='asis'}

# AEM by strata - Advanced readers #################################################

# Loop through each area and output AEM for that area
for (i in seq_along(ae_mat_by_strata_adv)) {
  # name of strata
  strata_name <- names(ae_mat_by_strata_adv)[i]
  
  # Table caption
  tempdat=t(as.data.frame(as.matrix(strsplit(strata_name, ", ")[[1]])))
  colnames(tempdat)=config$strata
  cap_i <- paste0("**Table X:** Age error matrix (AEM) for ", apply(tempdat, 1, function(x) {paste(str_to_title(config$strata), x, sep="_", collapse="_and_")}),".")
  
  set.caption(cap_i)
  pander(style_table3(ae_mat_by_strata_adv[[i]]), missing = "-")

}

```



<!-- Overall comparison of results by strata -->

```{r set_by_strata_adv}
# initialise strata loop
istrata <- 0
group <- "adv"
print_strata <- function() length(params$strata) >= istrata
```

```{r ref.label= 'strata_plus_one'}

```

```{r text_comparison, eval= print_strata()}

asis_output("***Overall comparison of results by strata***")

```  
  
```{r ar_by_strata_adv, eval= print_strata()}

group <- "adv"

# NUMBER OF AGE READINGS PER STOCK - Advanced readers #########################
# Table caption
set.caption('**Table X:** Number of age readings per strata and modal age for all advanced readers combined.')

# Output table
pander(style_table1(get(vname("num_read_tab_by_strata"))), missing = "-")
```

\

```{r text_comparison_adv_I, eval= print_strata()}

asis_output("*Coefficient of Variation (CV)*")

```  


```{r cv_by_strata_adv, eval= print_strata()}

# Table caption
set.caption('**Table X:** CV per strata and modal age for all advanced readers combined.')

# Output table
pander(style_table2(get(vname("cv_tab_by_strata"))), missing = "-")
```

\

```{r text_comparison_adv_II, eval= print_strata()}

asis_output("*Percentage of Agreement (PA)*")

```  

```{r pa_by_strata_adv, eval= print_strata()}
# Section title

# Table caption
set.caption('**Table X:** Percentage Agreement per strata and modal age for all advanced readers combined.')

# Output table
pander(style_table2(get(vname("pa_tab_by_strata"))), missing = "-")
```

\

```{r text_comparison_adv_III, eval= print_strata()}

asis_output("*Average Percentage Error (APE)*")

```  

```{r ape_by_strata_adv, eval= print_strata()}
# Section title

# Table caption
set.caption('**Table X:** Average Percentage Error per strata and modal age for all advanced readers combined.')

# Output table
pander(style_table2(get(vname("ape_tab_by_strata"))), missing = "-")
```

\

```{r text_comparison_adv_IV, eval= print_strata()}

asis_output("*Relative bias*")

```  

```{r rb_by_strata_adv, eval= print_strata()}
# Section title

# Table caption
set.caption('**Table X:** Relative Bias per strata and modal age for all advanced readers combined.')

# Output table
pander(style_table2(get(vname("rel_bias_tab_by_strata"))), missing = "-")
```

\

```{r text_comparison_adv_V, eval= print_strata()}

asis_output("*Growth analysis*")

```  

```{r growth_analysis_adv_by, fig.width = 8, fig.height = 4, fig.cap = cap_in, eval= print_strata()}
# GROWTH ANALYSIS - All readers ##########################################

# Table caption
cap_in <- '**Figure X:** Plot of average distance from the centre to the winter
           rings for all advanced readers by strata. The boxes represent 
           the median, upper and lower box boundaries of the interquartile range,
           whiskers represent the minimum and maximum values and the dots represent 
           the outliers.'

# Output table
plot_growth(dist, ad_long_adv, stratif = "all_strata")
```



# Conclusion



